### ISSUE TITLE
Not able to execute make from root user

### ISSUE THREAD

**Issue by janismdhanbad** [sh1ng/arboretum#37]
Hello, I am trying to install this from root user. I have added cub and  json as submodules but still, I am not able to execute the make, it is showing the following exact error

Ubuntu 16.04 with python3

root@instance-2:/home/janpreetds/arboretum# make
""  -gencode=arch=compute_61,code=\"sm_61,compute_61\"  -c -DSM610 -Xptxas -v -Xcudafe -#  -Xcompiler -ffloat-store -O3 -I_cub/ -I_json/src/ -std=c++11 -Xcompiler -fPIC -Xcompiler -O3 -Xcompiler -fopenmp -Xcompiler -Wall -Xcompiler -funroll-loops -Xcompiler -march=native -ccbin=g++ -o io.o src/io/io.cu
/bin/sh: 1: : Permission denied
makefile:31: recipe for target 'io.o' failed
make: *** [io.o] Error 127

Please help, thanks :)

**Comment by sh1ng** [comment]
For some reason compiler is empty "". Check that PATH contains location of cuda compiler(nvcc) and check cuda installation in general.

**Comment by EricPerbos** [comment]
Hello sh1ng

On Ubuntu 16.04 with python 3.6, makefile `export sm = 500`

$ make
"/usr/bin/nvcc"   -c  -Xptxas -v -Xcudafe -#  -Xcompiler -ffloat-store -O3 -I_cub/ -I_json/src/ -std=c++11 -Xcompiler -fPIC -Xcompiler -O3 -Xcompiler -fopenmp -Xcompiler -Wall -Xcompiler -funroll-loops -Xcompiler -march=native -ccbin=g++ -o io.o src/io/io.cu
/usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(36): error: identifier "__builtin_ia32_monitorx" is undefined

/usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(42): error: identifier "__builtin_ia32_mwaitx" is undefined

Front end time                       1.40 (CPU)       1.00 (elapsed)
2 errors detected in the compilation of "/tmp/tmpxft_00002054_00000000-7_io.cpp1.ii".
Total compilation time               1.41 (CPU)       1.00 (elapsed)
makefile:31: recipe for target 'io.o' failed
make: *** [io.o] Error 2


$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17

**Comment by sh1ng** [comment]
related probably
https://github.com/tensorflow/tensorflow/issues/1066

**Comment by kotestyle** [comment]
@janismdhanbad I had the same issue, cuda and was installed and worked fine with tensorflow, but in some way, there was no path to nvcc. So I just added 
```
export LD_LIBRARY_PATH=/usr/local/cuda/lib
export PATH=$PATH:/usr/local/cuda/bin
```
to .bashrc and it worked.

**Comment by janismdhanbad** [comment]
Hello @sh1ng , Thanks a lot, after reinstalling the cuda and following what @kotestyle said, it worked!!
:)

**Comment by yifanxie** [comment]
@EricPerbos in your case, add '-D_MWAITXINTRIN_H_INCLUDED -D_FORCE_INLINES -D__STRICT_ANSI__' at the end of your CFLAGG statement so it looks like 

`export CFLAGS = $(NVCCFLAGS) -O3 -I_cub/ -I_json/src/ -std=c++11 -Xcompiler -fPIC -Xcompiler -O3 -Xcompiler -fopenmp -Xcompiler -Wall -Xcompiler -funroll-loops -Xcompiler -march=native -ccbin=$(CXX) -D_MWAITXINTRIN_H_INCLUDED -D_FORCE_INLINES -D__STRICT_ANSI__`

In my installation (Ubuntu 16.04, Cuda 7.5), I also come across this [issue](https://github.com/nlohmann/json/issues/617), just follow the link for the solution there to change the file json.hpp

**Comment by lishubin** [comment]
maybe a noob qustion. i have gtx1070, what sm value should i assign?
i solve this issue by sudo su, and then 
export LD_LIBRARY_PATH=/usr/local/cuda/lib
export PATH=$PATH:/usr/local/cuda/bin

then it works

**Comment by janismdhanbad** [comment]
@lishubin , I have the same card, you can use the default value of 610, it works for me.

**Comment by lishubin** [comment]
@janismdhanbad 

now i cannot git glone the repo.something is changed :(

**Comment by janismdhanbad** [comment]
Oh, you're welcome @lishubin 
Oh, strange, I don't see any recent commits. Are you following the git --recursive thing? cause that worked for me

**Comment by lishubin** [comment]
someone from kaggle posted the same issue. the cub repo seems to have changed.. i cannot make this package to run.

**Comment by yifanxie** [comment]
@lishubin are you still struggling to build it? perhaps you can share the error message. I managed to get to up and running, perhasp with too low SM value, my GPU is only using a fraction of its VRAM

**Comment by sh1ng** [comment]
cub has been updated, probably irrelevant any more
