### ISSUE TITLE
error: can't copy '../python-wrapper/arboretum_wrapper.so': doesn't exist or not a regular file

### ISSUE THREAD

**Issue by EricPerbos** [sh1ng/arboretum#38]
When running `sudo python setup.py install`

running install
running bdist_egg
running egg_info
writing requirements to arboretum.egg-info/requires.txt
writing arboretum.egg-info/PKG-INFO
writing top-level names to arboretum.egg-info/top_level.txt
writing dependency_links to arboretum.egg-info/dependency_links.txt
reading manifest file 'arboretum.egg-info/SOURCES.txt'
writing manifest file 'arboretum.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
installing package data to build/bdist.linux-x86_64/egg
running install_data
error: can't copy '../python-wrapper/arboretum_wrapper.so': doesn't exist or not a regular file

**Comment by janismdhanbad** [comment]
Were you able to execute make file??

**Comment by EricPerbos** [comment]
No, the make command generates the same Error 127 you experienced so my ticket wasn't justified.
