### ISSUE TITLE
Cannot Find arboretum_wrapper.so

### ISSUE THREAD

**Issue by rydevera3** [sh1ng/arboretum#40]
I ran the README.md as directed everything was set up smoothly but when I tried to run the code it said it could not find the arboretum_wrapper.so in the python-wrapper directory. How can I remedy this? I ran this on Ubuntu.

**Comment by janismdhanbad** [comment]
@rydevera3 Hi, after running the make, arboretum_wrapper.so file is actually is made in another folder. You can copy and paste it into the python-package, that did the work for me.
