### ISSUE TITLE
Error cloning cub submodule

### ISSUE THREAD

**Issue by ebigelow** [sh1ng/arboretum#42]
When I run `git submodule update`, I get the error:

`fatal: reference is not a tree: 89de7ab20167909bc2c4f8acd397671c47cf3c0d`
`Unable to checkout '89de7ab20167909bc2c4f8acd397671c47cf3c0d' in submodule path '_cub'`

This error also showed up when I first cloned the arboretum repo. 

I can clone the newest version of cub, but this doesn't have the necessary file `cub/block/block_scan.cuh`. I also can't checkout the referenced commit, I get the error:

`$ git checkout 89de7ab20167909bc2c4f8acd397671c47cf3c0d .`
`fatal: reference is not a tree: 89de7ab20167909bc2c4f8acd397671c47cf3c0d`

**Comment by sh1ng** [comment]
fixed
