### ISSUE TITLE
using in windows

### ISSUE THREAD

**Issue by joaosauer** [sh1ng/arboretum#44]
Hi,

Is it possible to use your library in Windows?
I'm not able to find any info about that.
I believe that using mingw, I would be able to compile the project? Or is there anywhere in the web that I can find a compiled version?

Thanks,
Joao

**Comment by sh1ng** [comment]
Hi,

theoretically everything  is possible. 
I don't want to change the codebase a lot to compile and use it on windows. Ideally only a few lines in the make file. PR are welcome. 
As a workaround you could try docker container.

**Comment by joaosauer** [comment]
Hi,
So, I would be quite happy to do the necessary changes, but I'm quite newbie in compiling using make. But do you think that if I run mingw-make it would be a good start?
Also, What would be the docker container? A Virtual machine?

Cheers,
Joao

**Comment by sh1ng** [comment]
* It's good, but I'd advice check it compatibility with NVidia compiler on windows 
* Sort of
